services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - pg
      - es

  pg:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:5432
    attach: false

  # ms:
  #   image: getmeili/meilisearch:latest
  #   environment:
  #     - MEILI_MASTER_KEY=${MS_MASTER_KEY}
  #   ports:
  #     - ${MS_PORT}:7700
  #   attach: false

  es:
    image: elasticsearch:8.12.1
    environment:
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ES_PW}
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ports:
      - ${ES_PORT}:9200
    mem_limit: 416m
    attach: false
    command: >
      bash -c '
        bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      '
