services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - es

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:5432
    attach: false

  es:
    image: elasticsearch:8.12.1
    environment:
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ES_PW}
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - ${ES_PORT}:9200
    command: >
      bash -c '
        bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      '
    attach: false
