services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./src/adapter/pg/orm/schema.ts
    volumes:
      - ./src:/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      pg:
        condition: service_healthy

  pg:
    build:
      context: .
      dockerfile: dockerfile.pg
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER} -d ${PG_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 5s
