services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    volumes:
      - .:/app
    depends_on:
      - db
    attach: false

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    ports:
      - 5432:5432
    attach: false
