services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./src/adapter/pg/migration
        - action: rebuild
          path: ./src/adapter/pg/drizzle
    volumes:
      - ./src:/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      pg:
        condition: service_healthy
      ms:
        condition: service_healthy

  pg:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PW}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER} -d ${PG_DB}']
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 15s
      start_interval: 3s

  ms:
    image: getmeili/meilisearch:v1.12.7
    environment:
      - MEILI_MASTER_KEY=${MS_MASTER_KEY}
      - MEILI_LOG_LEVEL=ERROR
    ports:
      - ${MS_PORT}:7700
    volumes:
      - ms_data:/data.ms
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl http://localhost:7700/health || exit 1',
        ]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 15s
      start_interval: 3s

volumes:
  pg_data:
  ms_data:
